# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reddit.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0creddit.proto\"\x16\n\x04User\x12\x0e\n\x06userID\x18\x01 \x01(\t\"\xef\x01\n\x04Post\x12\x0e\n\x06postID\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0c\n\x04text\x18\x03 \x01(\t\x12\x10\n\x08mediaUrl\x18\x04 \x01(\t\x12\r\n\x05score\x18\x05 \x01(\t\x12\r\n\x05state\x18\x06 \x01(\t\x12\x17\n\x0fpublicationDate\x18\x07 \x01(\t\x12\x15\n\x06\x61uthor\x18\x08 \x01(\x0b\x32\x05.User\x12\x1c\n\x14post_created_message\x18\t \x01(\t\x12\x0e\n\x06upVote\x18\n \x01(\x05\x12\x10\n\x08\x64ownVote\x18\x0b \x01(\x05\x12\x1a\n\x08\x63omments\x18\x0c \x03(\x0b\x32\x08.Comment\"\xd1\x01\n\x07\x43omment\x12\x11\n\tcommentID\x18\x01 \x01(\t\x12\x15\n\x06\x61uthor\x18\x02 \x01(\x0b\x32\x05.User\x12\r\n\x05score\x18\x03 \x01(\t\x12\r\n\x05state\x18\x04 \x01(\t\x12\x17\n\x0fpublicationDate\x18\x05 \x01(\t\x12\x0e\n\x06upVote\x18\x06 \x01(\x05\x12\x10\n\x08\x64ownVote\x18\x07 \x01(\x05\x12\x13\n\x0bhas_replies\x18\x08 \x01(\t\x12\x19\n\x07replies\x18\t \x03(\x0b\x32\x08.Comment\x12\x13\n\x04post\x18\n \x01(\x0b\x32\x05.Post\"+\n\x04TopN\x12\x13\n\x04post\x18\x01 \x01(\x0b\x32\x05.Post\x12\x0e\n\x06number\x18\x02 \x01(\x05\"\x14\n\x06Update\x12\n\n\x02id\x18\x01 \x01(\t2\xa1\x02\n\x06Reddit\x12\x1c\n\nCreatePost\x12\x05.Post\x1a\x05.Post\"\x00\x12\x18\n\x06UpVote\x12\x05.Post\x1a\x05.Post\"\x00\x12\x1a\n\x08\x44ownVote\x12\x05.Post\x1a\x05.Post\"\x00\x12\x1a\n\x08Retrieve\x12\x05.Post\x1a\x05.Post\"\x00\x12%\n\rCreateComment\x12\x08.Comment\x1a\x08.Comment\"\x00\x12\x39\n\"RetrieveListOfNMostUpvotedComments\x12\x05.TopN\x1a\x08.Comment\"\x00\x30\x01\x12+\n\x13\x45xpandCommentBranch\x12\x08.Comment\x1a\x08.Comment\"\x00\x12\x18\n\x06Update\x12\x05.Post\x1a\x05.Post\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'reddit_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_USER']._serialized_start=16
  _globals['_USER']._serialized_end=38
  _globals['_POST']._serialized_start=41
  _globals['_POST']._serialized_end=280
  _globals['_COMMENT']._serialized_start=283
  _globals['_COMMENT']._serialized_end=492
  _globals['_TOPN']._serialized_start=494
  _globals['_TOPN']._serialized_end=537
  _globals['_UPDATE']._serialized_start=539
  _globals['_UPDATE']._serialized_end=559
  _globals['_REDDIT']._serialized_start=562
  _globals['_REDDIT']._serialized_end=851
# @@protoc_insertion_point(module_scope)
